apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  finalizers:
  - eventlisteners.triggers.tekton.dev
  name: el-gh-push
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: infracicd-push
