---

- hosts: dns-server 
  roles:
    - role: dns/config-dns-server-bind
  tasks:
    - name: Ensure files exist
      file:
        state: touch
        path: "{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - /etc/named/named.conf.acl
        - /etc/named/named.conf.tsig-keys
        - /etc/named/named.conf.view
    - name: Update zone file
      copy:
        src: "{{ inventory_dir }}/../files/rht-labs.io.zone"
        dest: /var/named/rht-labs.io.zone
        owner: root
        group: root
        mode: '0644'
    - name: Update forwarder
      lineinfile:
        path: /etc/named/named.conf.options
        line: "        forwarders { 10.217.4.10; };"
        insertafter: "^options"
    - name: Add zone to conf
      blockinfile:
        path: /etc/named.conf
        insertbefore: BOF
        block: |
          zone "rht-labs.io" IN {
              type master;
              file "rht-labs.io.zone";
          };
    - name: Restart service
      service:
        name: named
        state: restarted      
